#ifndef EVENTTABLE_H
#define EVENTTABLE_H

/*!
 * \brief The EventTable enum
 */
enum class EventTable { BUTTONCLICK, FRAMEENTER, FRAMEXIT, ACTIONTRIGERRED, GRIDSELECTEDCELL, PAINTEVENT };

#endif // EVENTTABLE_H
