QT += core gui widgets charts
TARGET = main
TEMPLATE = app
DEFINES += QT_DEPRECATED_WARNINGS
SOURCES += main.cpp \
    mid-button.cpp \
    mid-qt5-button.cpp \
    mid-qt5-window.cpp \
    window.cpp \
    mid-qt5-check-box.cpp \
    mid-qt5-progress-bar.cpp \
    mid-qt5-connect-factory.cpp \
    window_sample15.cpp \
    window_sample58.cpp \
    window_sample68.cpp \
    window_sample69.cpp \
    window_sample117.cpp \
    StringUtils.cpp

CONFIG += c++17 console
#CONFIG -= app_bundle

#HEADERS +=
HEADERS += \
    mid-button.h \
    mid-qt5-button.h \
    mid-application.h \
    mid-qt5-app.h \
    mid-qt5-window.h \
    mid-window.h \
    mid-qt5-msg-dialog.h \
    mid-msg-dialog.h \
    window.h \
    button.h \
    checkbox.h \
    textfield.h \
    mid-connect.h \
    mid-qt5-connect.h \
    eventtable.h \
    mid-handler.h \
    mid-object.h \
    mid-layout.h \
    midqtverticallayout.h \
    mid-qt5-horizontal-layout.h \
    mid-check-box.h \
    mid-qt5-check-box.h \    
    mid-radio-button.h \
    mid-qt5-radio-button.h \
    radio-button.h \
    mid-text-field.h \
    mid-qt5-text-field.h \
    progress-bar.h \
    mid-progress-bar.h \
    mid-qt5-progress-bar.h \
    textfield.h \
    mid-group-box.h \
    mid-qt5-group-box.h \
    group-box.h \
    mid-text-label.h \
    mid-qt5-text-label.h \
    textlabel.h \
    mid-combo-box.h \
    mid-qt5-combo-box.h \
    mid-spin-box.h \
    mid-qt5-spin-box.h \
    spin-box.h \
    combo-box.h \
    line.h \
    mid-line.h \
    mid-qt5-line.h \
    mid-date.h \
    mid-qt5-date.h \
    date.h \
    mid-date-edit.h \
    date-edit.h \
    mid-qt5-date-edit.h \
    mid-tab.h \
    mid-qt5-tab.h \
    tab.h \
    definitions.h \
    mid-panel.h \
    mid-qt5-panel.h \
    panel.h \
    mid-menu-bar.h \
    mid-qt5-menu-bar.h \
    menu-bar.h \
    mid-menu.h \
    mid-qt5-menu.h \
    menu.h \
    mid-layout.h \
    mid-qt5-button-handler.h \
    mid-button-handler.h \
    mid-action-handler.h \
    mid-qt5-action-handler.h \
    mid-action.h \
    mid-status-bar.h \
    mid-image.h \
    mid-list-box.h \
    mid-qt5-list-box.h \
    mid-tool-bar.h \
    mid-qt5-tool-bar.h \
    mid-image-label.h \
    mid-qt5-image.h \
    mid-qt5-status-bar.h \
    mid-qt5-action.h \
    action.h \
    textEdit.h \
    mid-text-edit.h \
    mid-qt5-text-edit.h \
    mid-qt5-gauge.h \
    mid-gauge.h \
    gauge.h \
    tabPage.h \
    mid-qt5-connect-factory.h \
    mid-canvas.h \
    mid-color.h \
    mid-qt5-colors.h \
    mid-qt5-image-label.h \
    mid-canvas.h \
    mid-color.h \
    mid-grid.h \
    mid-qt5-grid.h \
    mid-qt5-colors.h \
    mid-qt5-tree-widget.h \
    mid-tree-widget.h \
    mid-qt5-tree-widget-item.h \
    mid-qt5-tree-widget-subitem.h \
    treeWidget.h \
    mid-tree-widget-item.h \
    treeWidgetItem.h \
    treeWidgetSubitem.h \
    window_sample15.h \
    window_sample58.h \
    window_sample68.h \
    window_sample69.h \
    mid-qt5-tree-widget-subitem.h \
    treeWidgetSubitem.h \
    general.h \
    mid-grid-selected-cell-handler.h \
    mid-qt5-grid-selected-cell-handler.h \
    window_sample117.h \
    mid-qt5-group-action.h \
    mid-group-action.h \
    group-action.h \
    mid-qt5-file-dialog.h \
    mid-file-dialog.h \
    file-dialog.h \
    mid-qt5-dir-dialog.h \
    mid-dir-dialog.h \
    dir-dialog.h \
    mid-chart-view.h \
    mid-qt5-chart-view.h \
    mid-chart.h \
    mid-qt5-chart.h \
    StringUtils.h
